openapi: 3.0.0
info:
  description: Azure Maintenance Management Client
  title: MaintenanceManagementClient
  version: 2018-06-01-preview
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/maintenance/resource-manager/Microsoft.Maintenance/preview/2018-06-01-preview/Maintenance.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: maintenance-Maintenance
  x-tags:
    - Azure
    - Microsoft
paths:
  /providers/Microsoft.Maintenance/operations:
    get:
      description: List the available operations supported by the Microsoft.Maintenance
        resource provider
      operationId: Operations_List
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OperationsListResult"
              examples:
                Operations_List:
                  $ref: "#/components/examples/Operations_List"
        default:
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceError"
      summary: List available operations
      tags:
        - Operations
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/providers/Microsoft.Maintenance/maintenanceConfigurations":
    get:
      operationId: MaintenanceConfigurations_List
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListMaintenanceConfigurationsResult"
              examples:
                MaintenanceConfigurations_List:
                  $ref: "#/components/examples/MaintenanceConfigurations_List"
        default:
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceError"
      summary: Get Configuration records within a subscription
      tags:
        - MaintenanceConfigurations
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/Microsoft.Maintenance/maintenanceConfigurations/{resourceName}":
    delete:
      operationId: MaintenanceConfigurations_Delete
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource Group Name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            MaintenanceConfigurations_DeleteForResource:
              value: examplerg
        - description: Resource Identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            MaintenanceConfigurations_DeleteForResource:
              value: example1
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceConfiguration"
              examples:
                MaintenanceConfigurations_DeleteForResource:
                  $ref: "#/components/examples/MaintenanceConfigurations_DeleteForR\
                    esource"
        default:
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceError"
      summary: Delete Configuration record
      tags:
        - MaintenanceConfigurations
    get:
      operationId: MaintenanceConfigurations_Get
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource Group Name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            MaintenanceConfigurations_GetForResource:
              value: examplerg
        - description: Resource Identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            MaintenanceConfigurations_GetForResource:
              value: configuration1
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceConfiguration"
              examples:
                MaintenanceConfigurations_GetForResource:
                  $ref: "#/components/examples/MaintenanceConfigurations_GetForReso\
                    urce"
        default:
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceError"
      summary: Get Configuration record
      tags:
        - MaintenanceConfigurations
    patch:
      operationId: MaintenanceConfigurations_Update
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource Group Name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            MaintenanceConfigurations_UpdateForResource:
              value: examplerg
        - description: Resource Identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            MaintenanceConfigurations_UpdateForResource:
              value: configuration1
        - $ref: "#/components/parameters/ApiVersionParameter"
      requestBody:
        $ref: "#/components/requestBodies/MaintenanceConfiguration"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceConfiguration"
              examples:
                MaintenanceConfigurations_UpdateForResource:
                  $ref: "#/components/examples/MaintenanceConfigurations_UpdateForR\
                    esource"
        default:
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceError"
      summary: Patch configuration record
      tags:
        - MaintenanceConfigurations
    put:
      operationId: MaintenanceConfigurations_CreateOrUpdate
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource Group Name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            MaintenanceConfigurations_CreateOrUpdateForResource:
              value: examplerg
        - description: Resource Identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            MaintenanceConfigurations_CreateOrUpdateForResource:
              value: configuration1
        - $ref: "#/components/parameters/ApiVersionParameter"
      requestBody:
        $ref: "#/components/requestBodies/MaintenanceConfiguration"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceConfiguration"
              examples:
                MaintenanceConfigurations_CreateOrUpdateForResource:
                  $ref: "#/components/examples/MaintenanceConfigurations_CreateOrUp\
                    dateForResource"
        default:
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MaintenanceError"
      summary: Create or Update configuration record
      tags:
        - MaintenanceConfigurations
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{providerName}/{resourceParentType}/{resourceParentName}/{resourceType}/{resourceName}/providers/Microsoft.Maintenance/applyUpdates/default":
    put:
      description: Apply maintenance updates to resource with parent
      operationId: ApplyUpdates_CreateOrUpdateParent
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource group name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_CreateOrUpdateParent:
              value: examplerg
        - description: Resource provider name
          in: path
          name: providerName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_CreateOrUpdateParent:
              value: Microsoft.Compute
        - description: Resource parent type
          in: path
          name: resourceParentType
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_CreateOrUpdateParent:
              value: virtualMachineScaleSets
        - description: Resource parent identifier
          in: path
          name: resourceParentName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_CreateOrUpdateParent:
              value: smdtest1
        - description: Resource type
          in: path
          name: resourceType
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_CreateOrUpdateParent:
              value: virtualMachines
        - description: Resource identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_CreateOrUpdateParent:
              value: smdvm1
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplyUpdate"
              examples:
                ApplyUpdates_CreateOrUpdateParent:
                  $ref: "#/components/examples/ApplyUpdates_CreateOrUpdateParent"
      summary: Apply Updates to resource with parent
      tags:
        - ApplyUpdates
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{providerName}/{resourceParentType}/{resourceParentName}/{resourceType}/{resourceName}/providers/Microsoft.Maintenance/applyUpdates/{applyUpdateName}":
    get:
      description: Track maintenance updates to resource with parent
      operationId: ApplyUpdates_GetParent
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource group name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_GetParent:
              value: examplerg
        - description: Resource parent type
          in: path
          name: resourceParentType
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_GetParent:
              value: virtualMachineScaleSets
        - description: Resource parent identifier
          in: path
          name: resourceParentName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_GetParent:
              value: smdtest1
        - description: Resource provider name
          in: path
          name: providerName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_GetParent:
              value: Microsoft.Compute
        - description: Resource type
          in: path
          name: resourceType
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_GetParent:
              value: virtualMachines
        - description: Resource identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_GetParent:
              value: smdvm1
        - description: applyUpdate Id
          in: path
          name: applyUpdateName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_GetParent:
              value: e9b9685d-78e4-44c4-a81c-64a14f9b87b6
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplyUpdate"
              examples:
                ApplyUpdates_GetParent:
                  $ref: "#/components/examples/ApplyUpdates_GetParent"
      summary: Track Updates to resource with parent
      tags:
        - ApplyUpdates
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{providerName}/{resourceParentType}/{resourceParentName}/{resourceType}/{resourceName}/providers/Microsoft.Maintenance/configurationAssignments":
    get:
      description: List configurationAssignments for resource.
      operationId: ConfigurationAssignments_ListParent
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource group name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_ListParent:
              value: examplerg
        - description: Resource provider name
          in: path
          name: providerName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_ListParent:
              value: Microsoft.Compute
        - description: Resource parent type
          in: path
          name: resourceParentType
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_ListParent:
              value: virtualMachineScaleSets
        - description: Resource parent identifier
          in: path
          name: resourceParentName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_ListParent:
              value: smdtest1
        - description: Resource type
          in: path
          name: resourceType
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_ListParent:
              value: virtualMachines
        - description: Resource identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_ListParent:
              value: smdvm1
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListConfigurationAssignmentsResult"
              examples:
                ConfigurationAssignments_ListParent:
                  $ref: "#/components/examples/ConfigurationAssignments_ListParent"
      summary: List configurationAssignments for resource
      tags:
        - ConfigurationAssignments
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{providerName}/{resourceParentType}/{resourceParentName}/{resourceType}/{resourceName}/providers/Microsoft.Maintenance/configurationAssignments/{configurationAssignmentName}":
    delete:
      description: Unregister configuration for resource.
      operationId: ConfigurationAssignments_DeleteParent
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource group name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_DeleteParent:
              value: examplerg
        - description: Resource provider name
          in: path
          name: providerName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_DeleteParent:
              value: Microsoft.Compute
        - description: Resource parent type
          in: path
          name: resourceParentType
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_DeleteParent:
              value: virtualMachineScaleSets
        - description: Resource parent identifier
          in: path
          name: resourceParentName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_DeleteParent:
              value: smdtest1
        - description: Resource type
          in: path
          name: resourceType
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_DeleteParent:
              value: virtualMachines
        - description: Resource identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_DeleteParent:
              value: smdvm1
        - description: Unique configuration assignment name
          in: path
          name: configurationAssignmentName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_DeleteParent:
              value: workervmConfiguration
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfigurationAssignment"
              examples:
                ConfigurationAssignments_DeleteParent:
                  $ref: "#/components/examples/ConfigurationAssignments_DeleteParent"
      summary: Unregister configuration for resource
      tags:
        - ConfigurationAssignments
    put:
      description: Register configuration for resource.
      operationId: ConfigurationAssignments_CreateOrUpdateParent
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource group name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_CreateOrUpdateParent:
              value: examplerg
        - description: Resource provider name
          in: path
          name: providerName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_CreateOrUpdateParent:
              value: Microsoft.Compute
        - description: Resource parent type
          in: path
          name: resourceParentType
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_CreateOrUpdateParent:
              value: virtualMachineScaleSets
        - description: Resource parent identifier
          in: path
          name: resourceParentName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_CreateOrUpdateParent:
              value: smdtest1
        - description: Resource type
          in: path
          name: resourceType
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_CreateOrUpdateParent:
              value: virtualMachines
        - description: Resource identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_CreateOrUpdateParent:
              value: smdvm1
        - description: Configuration assignment name
          in: path
          name: configurationAssignmentName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_CreateOrUpdateParent:
              value: workervmPolicy
        - $ref: "#/components/parameters/ApiVersionParameter"
      requestBody:
        $ref: "#/components/requestBodies/ConfigurationAssignment"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfigurationAssignment"
              examples:
                ConfigurationAssignments_CreateOrUpdateParent:
                  $ref: "#/components/examples/ConfigurationAssignments_CreateOrUpd\
                    ateParent"
      summary: Create configuration assignment
      tags:
        - ConfigurationAssignments
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{providerName}/{resourceParentType}/{resourceParentName}/{resourceType}/{resourceName}/providers/Microsoft.Maintenance/updates":
    get:
      description: Get updates to resources.
      operationId: Updates_ListParent
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource group name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            Updates_ListParent:
              value: examplerg
        - description: Resource provider name
          in: path
          name: providerName
          required: true
          schema:
            type: string
          examples:
            Updates_ListParent:
              value: Microsoft.Compute
        - description: Resource parent type
          in: path
          name: resourceParentType
          required: true
          schema:
            type: string
          examples:
            Updates_ListParent:
              value: virtualMachineScaleSets
        - description: Resource parent identifier
          in: path
          name: resourceParentName
          required: true
          schema:
            type: string
          examples:
            Updates_ListParent:
              value: smdtest1
        - description: Resource type
          in: path
          name: resourceType
          required: true
          schema:
            type: string
          examples:
            Updates_ListParent:
              value: virtualMachines
        - description: Resource identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            Updates_ListParent:
              value: "1"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListUpdatesResult"
              examples:
                Updates_ListParent:
                  $ref: "#/components/examples/Updates_ListParent"
      summary: Get Updates to resource
      tags:
        - Updates
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{providerName}/{resourceType}/{resourceName}/providers/Microsoft.Maintenance/applyUpdates/default":
    put:
      description: Apply maintenance updates to resource
      operationId: ApplyUpdates_CreateOrUpdate
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource group name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_CreateOrUpdate:
              value: examplerg
        - description: Resource provider name
          in: path
          name: providerName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_CreateOrUpdate:
              value: Microsoft.Compute
        - description: Resource type
          in: path
          name: resourceType
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_CreateOrUpdate:
              value: virtualMachineScaleSets
        - description: Resource identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_CreateOrUpdate:
              value: smdtest1
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplyUpdate"
              examples:
                ApplyUpdates_CreateOrUpdate:
                  $ref: "#/components/examples/ApplyUpdates_CreateOrUpdate"
      summary: Apply Updates to resource
      tags:
        - ApplyUpdates
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{providerName}/{resourceType}/{resourceName}/providers/Microsoft.Maintenance/applyUpdates/{applyUpdateName}":
    get:
      description: Track maintenance updates to resource
      operationId: ApplyUpdates_Get
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource group name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_Get:
              value: examplerg
        - description: Resource provider name
          in: path
          name: providerName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_Get:
              value: Microsoft.Compute
        - description: Resource type
          in: path
          name: resourceType
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_Get:
              value: virtualMachineScaleSets
        - description: Resource identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_Get:
              value: smdtest1
        - description: applyUpdate Id
          in: path
          name: applyUpdateName
          required: true
          schema:
            type: string
          examples:
            ApplyUpdates_Get:
              value: e9b9685d-78e4-44c4-a81c-64a14f9b87b6
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplyUpdate"
              examples:
                ApplyUpdates_Get:
                  $ref: "#/components/examples/ApplyUpdates_Get"
      summary: Track Updates to resource
      tags:
        - ApplyUpdates
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{providerName}/{resourceType}/{resourceName}/providers/Microsoft.Maintenance/configurationAssignments":
    get:
      description: List configurationAssignments for resource.
      operationId: ConfigurationAssignments_List
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource group name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_List:
              value: examplerg
        - description: Resource provider name
          in: path
          name: providerName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_List:
              value: Microsoft.Compute
        - description: Resource type
          in: path
          name: resourceType
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_List:
              value: virtualMachineScaleSets
        - description: Resource identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_List:
              value: smdtest1
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListConfigurationAssignmentsResult"
              examples:
                ConfigurationAssignments_List:
                  $ref: "#/components/examples/ConfigurationAssignments_List"
      summary: List configurationAssignments for resource
      tags:
        - ConfigurationAssignments
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{providerName}/{resourceType}/{resourceName}/providers/Microsoft.Maintenance/configurationAssignments/{configurationAssignmentName}":
    delete:
      description: Unregister configuration for resource.
      operationId: ConfigurationAssignments_Delete
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource group name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_Delete:
              value: examplerg
        - description: Resource provider name
          in: path
          name: providerName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_Delete:
              value: Microsoft.Compute
        - description: Resource type
          in: path
          name: resourceType
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_Delete:
              value: virtualMachineScaleSets
        - description: Resource identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_Delete:
              value: smdtest1
        - description: Unique configuration assignment name
          in: path
          name: configurationAssignmentName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_Delete:
              value: workervmConfiguration
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfigurationAssignment"
              examples:
                ConfigurationAssignments_Delete:
                  $ref: "#/components/examples/ConfigurationAssignments_Delete"
      summary: Unregister configuration for resource
      tags:
        - ConfigurationAssignments
    put:
      description: Register configuration for resource.
      operationId: ConfigurationAssignments_CreateOrUpdate
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource group name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_CreateOrUpdate:
              value: examplerg
        - description: Resource provider name
          in: path
          name: providerName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_CreateOrUpdate:
              value: Microsoft.Compute
        - description: Resource type
          in: path
          name: resourceType
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_CreateOrUpdate:
              value: virtualMachineScaleSets
        - description: Resource identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_CreateOrUpdate:
              value: smdtest1
        - description: Configuration assignment name
          in: path
          name: configurationAssignmentName
          required: true
          schema:
            type: string
          examples:
            ConfigurationAssignments_CreateOrUpdate:
              value: workervmConfiguration
        - $ref: "#/components/parameters/ApiVersionParameter"
      requestBody:
        $ref: "#/components/requestBodies/ConfigurationAssignment"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfigurationAssignment"
              examples:
                ConfigurationAssignments_CreateOrUpdate:
                  $ref: "#/components/examples/ConfigurationAssignments_CreateOrUpd\
                    ate"
      summary: Create configuration assignment
      tags:
        - ConfigurationAssignments
  "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers/{providerName}/{resourceType}/{resourceName}/providers/Microsoft.Maintenance/updates":
    get:
      description: Get updates to resources.
      operationId: Updates_List
      parameters:
        - $ref: "#/components/parameters/SubscriptionIdParameter"
        - description: Resource group name
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            Updates_List:
              value: examplerg
        - description: Resource provider name
          in: path
          name: providerName
          required: true
          schema:
            type: string
          examples:
            Updates_List:
              value: Microsoft.Compute
        - description: Resource type
          in: path
          name: resourceType
          required: true
          schema:
            type: string
          examples:
            Updates_List:
              value: virtualMachineScaleSets
        - description: Resource identifier
          in: path
          name: resourceName
          required: true
          schema:
            type: string
          examples:
            Updates_List:
              value: smdtest1
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListUpdatesResult"
              examples:
                Updates_List:
                  $ref: "#/components/examples/Updates_List"
      summary: Get Updates to resource
      tags:
        - Updates
      x-ms-pageable: {}
servers:
  - url: https://management.azure.com
components:
  examples:
    Operations_List:
      value:
        value: []
    MaintenanceConfigurations_List:
      value:
        value:
          - id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Maintenance/maintenanceConfigurations/configuration1
            location: westus2
            name: configuration1
            properties:
              maintenanceScope: All
              namespace: Microsoft.Maintenance
    MaintenanceConfigurations_DeleteForResource:
      value:
        id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Maintenance/maintenanceConfigurations/configuration1
        location: westus2
        name: configuration1
        properties:
          namespace: Microsoft.Maintenance
    MaintenanceConfigurations_GetForResource:
      value:
        id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Maintenance/maintenanceConfigurations/configuration1
        location: westus2
        name: configuration1
        properties:
          maintenanceScope: All
          namespace: Microsoft.Maintenance
    MaintenanceConfigurations_UpdateForResource:
      value:
        id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Maintenance/maintenanceConfigurations/configuration1
        location: westus2
        name: configuration1
        properties:
          maintenanceScope: All
          namespace: Microsoft.Maintenance
    MaintenanceConfigurations_CreateOrUpdateForResource:
      value:
        id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Maintenance/maintenanceConfigurations/configuration1
        location: westus2
        name: configuration1
        properties:
          maintenanceScope: All
          namespace: Microsoft.Maintenance
    ApplyUpdates_CreateOrUpdateParent:
      value:
        id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/virtualMachines/smdvm1/providers/Microsoft.Maintenance/applyUpdates/e9b9685d-78e4-44c4-a81c-64a14f9b87b6
        name: e9b9685d-78e4-44c4-a81c-64a14f9b87b6
        properties:
          resourceId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/virtualMachines/smdvm1
          status: Pending
        type: Microsoft.Maintenance/applyUpdates
    ApplyUpdates_GetParent:
      value:
        id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/virtualMachines/smdvm1/providers/Microsoft.Maintenance/applyUpdates/e9b9685d-78e4-44c4-a81c-64a14f9b87b6
        name: e9b9685d-78e4-44c4-a81c-64a14f9b87b6
        properties:
          resourceId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/virtualMachines/smdvm1
          status: Completed
        type: Microsoft.Maintenance/applyUpdates
    ConfigurationAssignments_ListParent:
      value:
        value:
          - id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/virtualMachines/smdvm1/providers/Microsoft.Maintenance/configurationAssignments/workervmPolicy
            name: workervmPolicy
            properties:
              maintenanceConfigurationId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Maintenance/maintenanceConfigurations/policy1
              resourceId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/virtualMachines/smdvm1
            type: Microsoft.Maintenance/configurationAssignments
    ConfigurationAssignments_DeleteParent:
      value:
        id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/providers/Microsoft.Maintenance/configurationAssignments/workervmConfiguration
        name: workervmConfiguration
        type: Microsoft.Maintenance/configurationAssignments
    ConfigurationAssignments_CreateOrUpdateParent:
      value:
        id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/virtualMachines/smdvm1/providers/Microsoft.Maintenance/configurationAssignments/workervmPolicy
        name: workervmPolicy
        properties:
          maintenanceConfigurationId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Maintenance/maintenanceConfigurations/policy1
          resourceId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/virtualMachines/smdvm1
        type: Microsoft.Maintenance/configurationAssignments
    Updates_ListParent:
      value:
        value:
          - impactDurationInSec: 1440
            impactType: Reboot
            maintenanceScope: Resource
            notBefore: 2018-10-09T06:17:44.235Z
            properties:
              resourceId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/virtualMachines/1
            status: Pending
    ApplyUpdates_CreateOrUpdate:
      value:
        id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/providers/Microsoft.Maintenance/applyUpdates/e9b9685d-78e4-44c4-a81c-64a14f9b87b6
        name: e9b9685d-78e4-44c4-a81c-64a14f9b87b6
        properties:
          resourceId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1
          status: Pending
        type: Microsoft.Maintenance/applyUpdates
    ApplyUpdates_Get:
      value:
        id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/providers/Microsoft.Maintenance/applyUpdates/e9b9685d-78e4-44c4-a81c-64a14f9b87b6
        name: e9b9685d-78e4-44c4-a81c-64a14f9b87b6
        properties:
          resourceId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1
          status: Completed
        type: Microsoft.Maintenance/applyUpdates
    ConfigurationAssignments_List:
      value:
        value:
          - id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/providers/Microsoft.Maintenance/configurationAssignments/workervmConfiguration
            name: workervmConfiguration
            properties:
              maintenanceConfigurationId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Maintenance/maintenanceConfigurations/configuration1
              resourceId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1
            type: Microsoft.Maintenance/configurationAssignments
    ConfigurationAssignments_Delete:
      value:
        id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/providers/Microsoft.Maintenance/configurationAssignments/workervmConfiguration
        name: workervmConfiguration
        type: Microsoft.Maintenance/configurationAssignments
    ConfigurationAssignments_CreateOrUpdate:
      value:
        id: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1/providers/Microsoft.Maintenance/configurationAssignments/workervmConfiguration
        name: workervmConfiguration
        properties:
          maintenanceConfigurationId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Maintenance/maintenanceConfigurations/configuration1
          resourceId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1
        type: Microsoft.Maintenance/configurationAssignments
    Updates_List:
      value:
        value:
          - impactDurationInSec: 1440
            impactType: Reboot
            maintenanceScope: Resource
            notBefore: 2018-10-09T06:17:44.235Z
            properties:
              resourceId: /subscriptions/5b4b650e-28b9-4790-b3ab-ddbd88d727c4/resourcegroups/examplerg/providers/Microsoft.Compute/virtualMachineScaleSets/smdtest1
            status: Pending
  parameters:
    ApiVersionParameter:
      description: Version of the API to be used with the client request.
      in: query
      name: api-version
      required: true
      schema:
        type: string
      examples:
        Operations_List:
          value: 2018-06-01-preview
        MaintenanceConfigurations_List:
          value: 2018-06-01-preview
        MaintenanceConfigurations_DeleteForResource:
          value: 2018-06-01-preview
        MaintenanceConfigurations_GetForResource:
          value: 2018-06-01-preview
        MaintenanceConfigurations_UpdateForResource:
          value: 2018-06-01-preview
        MaintenanceConfigurations_CreateOrUpdateForResource:
          value: 2018-06-01-preview
        ApplyUpdates_CreateOrUpdateParent:
          value: 2018-06-01-preview
        ApplyUpdates_GetParent:
          value: 2018-06-01-preview
        ConfigurationAssignments_ListParent:
          value: 2018-06-01-preview
        ConfigurationAssignments_DeleteParent:
          value: 2018-06-01-preview
        ConfigurationAssignments_CreateOrUpdateParent:
          value: 2018-06-01-preview
        Updates_ListParent:
          value: 2018-06-01-preview
        ApplyUpdates_CreateOrUpdate:
          value: 2018-06-01-preview
        ApplyUpdates_Get:
          value: 2018-06-01-preview
        ConfigurationAssignments_List:
          value: 2018-06-01-preview
        ConfigurationAssignments_Delete:
          value: 2018-06-01-preview
        ConfigurationAssignments_CreateOrUpdate:
          value: 2018-06-01-preview
        Updates_List:
          value: 2018-06-01-preview
    SubscriptionIdParameter:
      description: Subscription credentials that uniquely identify a Microsoft Azure
        subscription. The subscription ID forms part of the URI for every
        service call.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
      examples:
        MaintenanceConfigurations_List:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        MaintenanceConfigurations_DeleteForResource:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        MaintenanceConfigurations_GetForResource:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        MaintenanceConfigurations_UpdateForResource:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        MaintenanceConfigurations_CreateOrUpdateForResource:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        ApplyUpdates_CreateOrUpdateParent:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        ApplyUpdates_GetParent:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        ConfigurationAssignments_ListParent:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        ConfigurationAssignments_DeleteParent:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        ConfigurationAssignments_CreateOrUpdateParent:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        Updates_ListParent:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        ApplyUpdates_CreateOrUpdate:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        ApplyUpdates_Get:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        ConfigurationAssignments_List:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        ConfigurationAssignments_Delete:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        ConfigurationAssignments_CreateOrUpdate:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
        Updates_List:
          value: 5b4b650e-28b9-4790-b3ab-ddbd88d727c4
  requestBodies:
    MaintenanceConfiguration:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MaintenanceConfiguration"
      description: The configuration
      required: true
    ConfigurationAssignment:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ConfigurationAssignment"
      description: The configurationAssignment
      required: true
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ApplyUpdate:
      allOf:
        - $ref: "#/components/schemas/Resource"
      description: Apply Update request
      properties:
        properties:
          $ref: "#/components/schemas/ApplyUpdateProperties"
      type: object
    ApplyUpdateProperties:
      description: Properties for apply update
      properties:
        lastUpdateTime:
          description: Last Update time
          format: date-time
          type: string
        resourceId:
          description: The resourceId
          type: string
        status:
          description: The status
          enum:
            - Pending
            - InProgress
            - Completed
            - RetryNow
            - RetryLater
          type: string
          x-ms-enum:
            modelAsString: true
            name: UpdateStatus
      type: object
    ConfigurationAssignment:
      allOf:
        - $ref: "#/components/schemas/Resource"
      description: Configuration Assignment
      properties:
        location:
          description: Location of the resource
          type: string
        properties:
          $ref: "#/components/schemas/ConfigurationAssignmentProperties"
      type: object
    ConfigurationAssignmentProperties:
      description: Properties for configuration assignment
      properties:
        maintenanceConfigurationId:
          description: The maintenance configuration Id
          type: string
        resourceId:
          description: The unique resourceId
          type: string
      type: object
    ErrorDetails:
      description: An error response details received from the Azure Maintenance service.
      properties:
        code:
          description: Service-defined error code. This code serves as a sub-status for the
            HTTP error code specified in the response.
          type: string
        message:
          description: Human-readable representation of the error.
          type: string
      type: object
    ListConfigurationAssignmentsResult:
      description: Response for ConfigurationAssignments list
      properties:
        value:
          description: The list of configuration Assignments
          items:
            $ref: "#/components/schemas/ConfigurationAssignment"
          type: array
      type: object
    ListMaintenanceConfigurationsResult:
      description: Response for MaintenanceConfigurations list
      properties:
        value:
          description: The list of maintenance Configurations
          items:
            $ref: "#/components/schemas/MaintenanceConfiguration"
          type: array
      type: object
    ListUpdatesResult:
      description: Response for Updates list
      properties:
        value:
          description: The pending updates
          items:
            $ref: "#/components/schemas/Update"
          type: array
      type: object
    MaintenanceConfiguration:
      allOf:
        - $ref: "#/components/schemas/Resource"
      description: Maintenance configuration record type
      properties:
        location:
          description: Gets or sets location of the resource
          type: string
        properties:
          $ref: "#/components/schemas/MaintenanceConfigurationProperties"
        tags:
          additionalProperties:
            type: string
          description: Gets or sets tags of the resource
          type: object
      type: object
    MaintenanceConfigurationProperties:
      description: Properties for maintenance configuration
      properties:
        extensionProperties:
          additionalProperties:
            type: string
          description: Gets or sets extensionProperties of the maintenanceConfiguration
          type: object
        maintenanceScope:
          description: Gets or sets maintenanceScope of the configuration
          enum:
            - All
            - Host
            - Resource
            - InResource
          type: string
          x-ms-enum:
            modelAsString: true
            name: MaintenanceScope
        namespace:
          description: Gets or sets namespace of the resource
          type: string
      type: object
    MaintenanceError:
      description: An error response received from the Azure Maintenance service.
      properties:
        error:
          $ref: "#/components/schemas/ErrorDetails"
      type: object
    Operation:
      description: Represents an operation returned by the GetOperations request
      properties:
        display:
          $ref: "#/components/schemas/OperationInfo"
        name:
          description: Name of the operation
          type: string
        origin:
          description: Origin of the operation
          type: string
        properties:
          description: Properties of the operation
          type: object
          x-ms-client-flatten: true
      type: object
    OperationInfo:
      description: Information about an operation
      properties:
        description:
          description: Description of the operation
          type: string
        operation:
          description: Name of the operation
          type: string
        provider:
          description: Name of the provider
          type: string
        resource:
          description: Name of the resource type
          type: string
      type: object
    OperationsListResult:
      description: Result of the List Operations operation
      properties:
        value:
          description: A collection of operations
          items:
            $ref: "#/components/schemas/Operation"
          type: array
      type: object
    Resource:
      description: Definition of a Resource
      properties:
        id:
          description: Fully qualified identifier of the resource
          readOnly: true
          type: string
        name:
          description: Name of the resource
          readOnly: true
          type: string
        type:
          description: Type of the resource
          readOnly: true
          type: string
      type: object
      x-ms-azure-resource: true
    Update:
      description: Maintenance update on a resource
      properties:
        impactDurationInSec:
          description: Duration of impact in seconds
          format: int32
          type: integer
        impactType:
          description: The impact type
          enum:
            - None
            - Freeze
            - Restart
            - Redeploy
          type: string
          x-ms-enum:
            modelAsString: true
            name: ImpactType
        maintenanceScope:
          description: The impact area
          enum:
            - All
            - Host
            - Resource
            - InResource
          type: string
          x-ms-enum:
            modelAsString: true
            name: MaintenanceScope
        notBefore:
          description: Time when Azure will start force updates if not self-updated by
            customer before this time
          format: date-time
          type: string
        properties:
          $ref: "#/components/schemas/UpdateProperties"
        status:
          description: The status
          enum:
            - Pending
            - InProgress
            - Completed
            - RetryNow
            - RetryLater
          type: string
          x-ms-enum:
            modelAsString: true
            name: UpdateStatus
      type: object
    UpdateProperties:
      description: Properties for update
      properties:
        resourceId:
          description: The resourceId
          type: string
      type: object
