openapi: 3.0.0
info:
  title: AutomationManagement
  version: 2015-10-31
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/automation/resource-manager/Microsoft.Automation/stable/2015-10-31/account.json
      version: "2.0"
  x-providerName: azure.com
  x-serviceName: automation-account
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  /providers/Microsoft.Automation/operations:
    get:
      description: Lists all of the available Automation REST API operations.
      operationId: Operations_List
      parameters:
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OperationListResult"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - Operations
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/providers/Microsoft.Automation/automationAccounts":
    get:
      description: Retrieve a list of accounts within a given subscription.
      operationId: AutomationAccount_List
      parameters:
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            List automation accounts by resource group:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            List automation accounts by resource group:
              value: 2015-10-31
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AutomationAccountListResult"
              examples:
                List automation accounts by resource group:
                  $ref: "#/components/examples/List_automation_accounts_by_resource\
                    _group"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      summary: Lists the Automation Accounts within an Azure subscription.
      tags:
        - AutomationAccount
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts":
    get:
      description: Retrieve a list of accounts within a given resource group.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/automationaccountoperations
      operationId: AutomationAccount_ListByResourceGroup
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            List automation accounts by resource group:
              value: rg
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            List automation accounts by resource group:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            List automation accounts by resource group:
              value: 2015-10-31
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AutomationAccountListResult"
              examples:
                List automation accounts by resource group:
                  $ref: "#/components/examples/List_automation_accounts_by_resource\
                    _group"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - AutomationAccount
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}":
    delete:
      description: Delete an automation account.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/automationaccountoperations
      operationId: AutomationAccount_Delete
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Delete automation account:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Delete automation account:
              value: myAutomationAccount9
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Delete automation account:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Delete automation account:
              value: 2015-10-31
      responses:
        "200":
          description: OK
        "204":
          description: No Content
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - AutomationAccount
    get:
      description: Get information about an Automation Account.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/automationaccountoperations
      operationId: AutomationAccount_Get
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Get automation account:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get automation account:
              value: myAutomationAccount9
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get automation account:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get automation account:
              value: 2015-10-31
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AutomationAccount"
              examples:
                Get automation account:
                  $ref: "#/components/examples/Get_automation_account"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - AutomationAccount
    patch:
      description: Update an automation account.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/automationaccountoperations
      operationId: AutomationAccount_Update
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Update an automation account:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Update an automation account:
              value: myAutomationAccount9
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Update an automation account:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Update an automation account:
              value: 2015-10-31
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AutomationAccountUpdateParameters"
        description: Parameters supplied to the update automation account.
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AutomationAccount"
              examples:
                Update an automation account:
                  $ref: "#/components/examples/Update_an_automation_account"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - AutomationAccount
    put:
      description: Create or update automation account.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/automationaccountoperations
      operationId: AutomationAccount_CreateOrUpdate
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Create or update automation account:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Create or update automation account:
              value: myAutomationAccount9
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Create or update automation account:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Create or update automation account:
              value: 2015-10-31
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AutomationAccountCreateOrUpdateParameters"
        description: Parameters supplied to the create or update automation account.
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AutomationAccount"
              examples:
                Create or update automation account:
                  $ref: "#/components/examples/Create_or_update_automation_account"
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AutomationAccount"
              examples:
                Create or update automation account:
                  $ref: "#/components/examples/Create_or_update_automation_account"
        default:
          description: Automation error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - AutomationAccount
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/listKeys":
    post:
      description: Retrieve the automation keys for an account.
      operationId: Keys_ListByAutomationAccount
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Get lists of an automation account:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get lists of an automation account:
              value: MyAutomationAccount
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get lists of an automation account:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get lists of an automation account:
              value: 2015-10-31
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/KeyListResult"
              examples:
                Get lists of an automation account:
                  $ref: "#/components/examples/Get_lists_of_an_automation_account"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - ListKeys
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/statistics":
    get:
      description: Retrieve the statistics for the account.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/statisticsoperations
      operationId: Statistics_ListByAutomationAccount
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Get statistics of an automation account:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get statistics of an automation account:
              value: myAutomationAccount11
        - description: The filter to apply on the operation.
          in: query
          name: $filter
          required: false
          schema:
            type: string
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get statistics of an automation account:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get statistics of an automation account:
              value: 2015-10-31
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatisticsListResult"
              examples:
                Get statistics of an automation account:
                  $ref: "#/components/examples/Get_statistics_of_an_automation_acco\
                    unt"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - Statistics
      x-ms-pageable: {}
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}/usages":
    get:
      description: Retrieve the usage for the account id.
      externalDocs:
        url: http://aka.ms/azureautomationsdk/usageoperations
      operationId: Usages_ListByAutomationAccount
      parameters:
        - description: Name of an Azure Resource group.
          in: path
          name: resourceGroupName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
            minLength: 1
            maxLength: 90
            pattern: ^[-\w\._]+$
          examples:
            Get usages of an automation account:
              value: rg
        - description: The name of the automation account.
          in: path
          name: automationAccountName
          required: true
          x-ms-parameter-location: method
          schema:
            type: string
          examples:
            Get usages of an automation account:
              value: myAutomationAccount11
        - description: Gets subscription credentials which uniquely identify Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            Get usages of an automation account:
              value: subid
        - description: Client Api Version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            Get usages of an automation account:
              value: 2015-10-31
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsageListResult"
              examples:
                Get usages of an automation account:
                  $ref: "#/components/examples/Get_usages_of_an_automation_account"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                description: Error response of an operation failure
                properties:
                  code:
                    description: Error code
                    type: string
                  message:
                    description: Error message indicating why the operation failed.
                    type: string
                type: object
      tags:
        - Usages
      x-ms-pageable: {}
servers:
  - url: https://management.azure.com
components:
  examples:
    List_automation_accounts_by_resource_group:
      value:
        value:
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myaccount
            location: eastus2
            name: myaccount
            properties:
              creationTime: 2016-09-24T00:47:04.227+00:00
              lastModifiedBy: myEmailId@microsoft.com
              lastModifiedTime: 2017-02-09T21:35:16.4+00:00
              state: Ok
            type: Microsoft.Automation/AutomationAccounts
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAccount123
            location: eastus2
            name: myAccount123
            properties:
              creationTime: 2016-09-29T00:32:32.52+00:00
              lastModifiedBy: myEmailId@microsoft.com
              lastModifiedTime: 2017-02-09T21:35:16.4+00:00
              state: Ok
            type: Microsoft.Automation/AutomationAccounts
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAccountasfads
            location: East US 2
            name: myAccountasfads
            properties:
              creationTime: 2017-03-24T23:21:03.27+00:00
              lastModifiedBy: myEmailId@microsoft.com
              lastModifiedTime: 2017-03-24T23:21:03.27+00:00
              state: Ok
            type: Microsoft.Automation/AutomationAccounts
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount1
            location: East US 2
            name: myAutomationAccount1
            properties:
              creationTime: 2017-03-24T23:22:33.26+00:00
              lastModifiedBy: myEmailId@microsoft.com
              lastModifiedTime: 2017-03-24T23:22:33.26+00:00
              state: Ok
            type: Microsoft.Automation/AutomationAccounts
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11
            location: East US 2
            name: myAutomationAccount11
            properties:
              creationTime: 2017-03-26T02:10:24.523+00:00
              lastModifiedBy: myEmailId@microsoft.com
              lastModifiedTime: 2017-03-26T02:11:12.027+00:00
              state: Ok
            type: Microsoft.Automation/AutomationAccounts
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount2
            location: East US 2
            name: myAutomationAccount2
            properties:
              creationTime: 2017-03-24T23:24:20.31+00:00
              lastModifiedBy: myEmailId@microsoft.com
              lastModifiedTime: 2017-03-24T23:24:20.31+00:00
              state: Ok
            type: Microsoft.Automation/AutomationAccounts
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount3
            location: East US 2
            name: myAutomationAccount3
            properties:
              creationTime: 2017-03-24T23:24:43.967+00:00
              lastModifiedBy: myEmailId@microsoft.com
              lastModifiedTime: 2017-03-24T23:24:43.967+00:00
              state: Ok
            type: Microsoft.Automation/AutomationAccounts
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount4
            location: East US 2
            name: myAutomationAccount4
            properties:
              creationTime: 2017-03-25T02:04:56.9+00:00
              lastModifiedBy: myEmailId@microsoft.com
              lastModifiedTime: 2017-03-25T02:04:56.9+00:00
              state: Ok
            type: Microsoft.Automation/AutomationAccounts
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount6
            location: East US 2
            name: myAutomationAccount6
            properties:
              creationTime: 2017-03-25T02:10:44.567+00:00
              lastModifiedBy: myEmailId@microsoft.com
              lastModifiedTime: 2017-03-25T02:10:44.567+00:00
              state: Ok
            type: Microsoft.Automation/AutomationAccounts
          - id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount7
            location: East US 2
            name: myAutomationAccount7
            properties:
              creationTime: 2017-03-25T02:19:17.943+00:00
              lastModifiedBy: myEmailId@microsoft.com
              lastModifiedTime: 2017-03-25T02:19:17.943+00:00
              state: Ok
            type: Microsoft.Automation/AutomationAccounts
    Get_automation_account:
      value:
        id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount9
        location: East US 2
        name: myAutomationAccount9
        properties:
          creationTime: 2017-03-26T01:13:43.267+00:00
          lastModifiedBy: myEmailId@microsoft.com
          lastModifiedTime: 2017-03-26T01:13:43.267+00:00
          sku:
            name: Free
          state: Ok
        tags: {}
        type: Microsoft.Automation/AutomationAccounts
    Update_an_automation_account:
      value:
        id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount9
        location: East US 2
        name: myAutomationAccount9
        properties:
          creationTime: 2017-03-26T01:13:43.267+00:00
          lastModifiedBy: myEmailId@microsoft.com
          lastModifiedTime: 2017-03-26T01:13:43.267+00:00
          sku:
            name: Free
          state: Ok
        tags: {}
        type: Microsoft.Automation/AutomationAccounts
    Create_or_update_automation_account:
      value:
        id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount9
        location: East US 2
        name: myAutomationAccount9
        properties:
          creationTime: 2017-03-26T01:13:43.267+00:00
          lastModifiedBy: myEmailId@microsoft.com
          lastModifiedTime: 2017-03-26T01:13:43.267+00:00
          sku:
            name: Free
          state: Ok
        tags: {}
        type: Microsoft.Automation/AutomationAccounts
    Get_lists_of_an_automation_account:
      value:
        keys:
          - KeyName: Primary
            Permissions: Full
            Value: "**************************************************************"
          - KeyName: Secondary
            Permissions: Full
            Value: "**************************************************************"
    Get_statistics_of_an_automation_account:
      value:
        value:
          - counterProperty: New
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/New
            startTime: 2017-03-19T02:11:49.9879197+00:00
          - counterProperty: Activating
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/Activating
            startTime: 2017-03-19T02:11:49.9879197+00:00
          - counterProperty: Running
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/Running
            startTime: 2017-03-19T02:11:49.9879197+00:00
          - counterProperty: Completed
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/Completed
            startTime: 2017-03-19T02:11:49.9879197+00:00
          - counterProperty: Failed
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/Failed
            startTime: 2017-03-19T02:11:49.9879197+00:00
          - counterProperty: Stopped
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/Stopped
            startTime: 2017-03-19T02:11:49.9879197+00:00
          - counterProperty: Blocked
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/Blocked
            startTime: 2017-03-19T02:11:49.9879197+00:00
          - counterProperty: Suspended
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/Suspended
            startTime: 2017-03-19T02:11:49.9879197+00:00
          - counterProperty: Disconnected
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/Disconnected
            startTime: 2017-03-19T02:11:49.9879197+00:00
          - counterProperty: Suspending
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/Suspending
            startTime: 2017-03-19T02:11:49.9879197+00:00
          - counterProperty: Stopping
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/Stopping
            startTime: 2017-03-19T02:11:49.9879197+00:00
          - counterProperty: Resuming
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/Resuming
            startTime: 2017-03-19T02:11:49.9879197+00:00
          - counterProperty: Removing
            counterValue: 0
            endTime: 2017-03-26T02:11:49.9879197+00:00
            id: /subscriptions/subid/resourceGroups/rg/providers/Microsoft.Automation/automationAccounts/myAutomationAccount11/statistics/Removing
            startTime: 2017-03-19T02:11:49.9879197+00:00
    Get_usages_of_an_automation_account:
      value:
        value:
          - currentValue: 0
            limit: 500
            name:
              localizedValue: AccountUsage
              value: AccountUsage
            throttleStatus: NotThrottled
            unit: Minute
          - currentValue: 429
            limit: 500
            name:
              localizedValue: SubscriptionUsage
              value: SubscriptionUsage
            throttleStatus: NotThrottled
            unit: Minute
          - currentValue: 8
            limit: 5
            name:
              localizedValue: DscSubscriptionUsage
              value: DscSubscriptionUsage
            throttleStatus: ThrottledAtSubscriptionLevel
            unit: Count
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    AutomationAccount:
      allOf:
        - allOf:
            - description: The core properties of ARM resources
              properties:
                id:
                  description: Fully qualified resource Id for the resource
                  readOnly: true
                  type: string
                name:
                  description: The name of the resource
                  readOnly: true
                  type: string
                type:
                  description: The type of the resource.
                  readOnly: true
                  type: string
              type: object
              x-ms-azure-resource: true
          description: The resource model definition for a ARM tracked top level resource
          properties:
            location:
              description: The Azure Region where the resource lives
              type: string
              x-ms-mutability:
                - read
                - create
            tags:
              additionalProperties:
                type: string
              description: Resource tags.
              type: object
              x-ms-mutability:
                - read
                - create
                - update
          type: object
      description: Definition of the automation account type.
      properties:
        etag:
          description: Gets or sets the etag of the resource.
          type: string
        properties:
          $ref: "#/components/schemas/AutomationAccountProperties"
    AutomationAccountCreateOrUpdateParameters:
      description: The parameters supplied to the create or update automation account
        operation.
      properties:
        location:
          description: Gets or sets the location of the resource.
          type: string
        name:
          description: Gets or sets name of the resource.
          type: string
        properties:
          $ref: "#/components/schemas/AutomationAccountCreateOrUpdateProperties"
        tags:
          additionalProperties:
            type: string
          description: Gets or sets the tags attached to the resource.
          type: object
    AutomationAccountCreateOrUpdateProperties:
      description: The parameters supplied to the create or update account properties.
      properties:
        sku:
          $ref: "#/components/schemas/Sku"
    AutomationAccountListResult:
      description: The response model for the list account operation.
      properties:
        nextLink:
          description: Gets or sets the next link.
          type: string
        value:
          description: Gets or sets list of accounts.
          items:
            $ref: "#/components/schemas/AutomationAccount"
          type: array
    AutomationAccountProperties:
      description: Definition of the account property.
      properties:
        creationTime:
          description: Gets the creation time.
          format: date-time
          readOnly: true
          type: string
          nullable: false
        description:
          description: Gets or sets the description.
          type: string
        lastModifiedBy:
          description: Gets or sets the last modified by.
          type: string
        lastModifiedTime:
          description: Gets the last modified time.
          format: date-time
          readOnly: true
          type: string
          nullable: false
        sku:
          $ref: "#/components/schemas/Sku"
        state:
          description: Gets status of account.
          enum:
            - Ok
            - Unavailable
            - Suspended
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: AutomationAccountState
    AutomationAccountUpdateParameters:
      description: The parameters supplied to the update automation account operation.
      properties:
        location:
          description: Gets or sets the location of the resource.
          type: string
        name:
          description: Gets or sets the name of the resource.
          type: string
        properties:
          $ref: "#/components/schemas/AutomationAccountUpdateProperties"
        tags:
          additionalProperties:
            type: string
          description: Gets or sets the tags attached to the resource.
          type: object
    AutomationAccountUpdateProperties:
      description: The parameters supplied to the update account properties.
      properties:
        sku:
          $ref: "#/components/schemas/Sku"
    Key:
      description: Automation key which is used to register a DSC Node
      properties:
        KeyName:
          description: Automation key name.
          enum:
            - Primary
            - Secondary
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: AutomationKeyName
        Permissions:
          description: Automation key permissions.
          enum:
            - Read
            - Full
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: AutomationKeyPermissions
        Value:
          description: Value of the Automation Key used for registration.
          readOnly: true
          type: string
    KeyListResult:
      properties:
        keys:
          description: Lists the automation keys.
          items:
            $ref: "#/components/schemas/Key"
          type: array
    Operation:
      description: Automation REST API operation
      properties:
        display:
          description: Provider, Resource and Operation values
          properties:
            operation:
              description: "Operation type: Read, write, delete, etc."
              type: string
            provider:
              description: "Service provider: Microsoft.Automation"
              type: string
            resource:
              description: "Resource on which the operation is performed: Runbooks, Jobs
                etc."
              type: string
        name:
          description: "Operation name: {provider}/{resource}/{operation}"
          type: string
      type: object
    OperationListResult:
      description: The response model for the list of Automation operations
      properties:
        value:
          description: List of Automation operations supported by the Automation resource
            provider.
          items:
            $ref: "#/components/schemas/Operation"
          type: array
    Sku:
      description: The account SKU.
      properties:
        capacity:
          description: Gets or sets the SKU capacity.
          format: int32
          type: integer
        family:
          description: Gets or sets the SKU family.
          type: string
        name:
          description: Gets or sets the SKU name of the account.
          enum:
            - Free
            - Basic
          type: string
          x-ms-enum:
            modelAsString: true
            name: SkuNameEnum
      required:
        - name
    Statistics:
      description: Definition of the statistic.
      properties:
        counterProperty:
          description: Gets the property value of the statistic.
          readOnly: true
          type: string
        counterValue:
          description: Gets the value of the statistic.
          format: int64
          readOnly: true
          type: integer
        endTime:
          description: Gets the endTime of the statistic.
          format: date-time
          readOnly: true
          type: string
          nullable: true
        id:
          description: Gets the id.
          readOnly: true
          type: string
        startTime:
          description: Gets the startTime of the statistic.
          format: date-time
          readOnly: true
          type: string
          nullable: false
    StatisticsListResult:
      description: The response model for the list statistics operation.
      properties:
        value:
          description: Gets or sets a list of statistics.
          items:
            $ref: "#/components/schemas/Statistics"
          type: array
    Usage:
      description: Definition of Usage.
      properties:
        currentValue:
          description: Gets or sets the current usage value.
          format: double
          type: number
        id:
          description: Gets or sets the id of the resource.
          type: string
        limit:
          description: Gets or sets max limit. -1 for unlimited
          format: int64
          type: integer
        name:
          $ref: "#/components/schemas/UsageCounterName"
        throttleStatus:
          description: Gets or sets the throttle status.
          type: string
        unit:
          description: Gets or sets the usage unit name.
          type: string
    UsageCounterName:
      description: Definition of usage counter name.
      properties:
        localizedValue:
          description: Gets or sets the localized usage counter name.
          type: string
        value:
          description: Gets or sets the usage counter name.
          type: string
    UsageListResult:
      description: The response model for the get usage operation.
      properties:
        value:
          description: Gets or sets usage.
          items:
            $ref: "#/components/schemas/Usage"
          type: array
