openapi: 3.0.0
info:
  description: The Microsoft Azure Network management API provides a RESTful set of web
    services that interact with Microsoft Azure Networks service to manage your
    network resources. The API has entities that capture the relationship
    between an end user and the Microsoft Azure Networks service.
  title: NetworkManagementClient
  version: 2019-04-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/network/resource-manager/Microsoft.Network/stable/2019-04-01/expressRouteGateway.json
      version: "2.0"
  x-preferred: false
  x-providerName: azure.com
  x-serviceName: network-expressRouteGateway
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Network/expressRouteGateways":
    get:
      description: Lists ExpressRoute gateways under a given subscription.
      operationId: ExpressRouteGateways_ListBySubscription
      parameters:
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayListBySubscription:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayListBySubscription:
              value: subid
      responses:
        "200":
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpressRouteGatewayList"
              examples:
                ExpressRouteGatewayListBySubscription:
                  $ref: "#/components/examples/ExpressRouteGatewayListBySubscription"
      tags:
        - ExpressRouteGateways
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteGateways":
    get:
      description: Lists ExpressRoute gateways in a given resource group.
      operationId: ExpressRouteGateways_ListByResourceGroup
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayListByResourceGroup:
              value: resourceGroupName
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayListByResourceGroup:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayListByResourceGroup:
              value: subid
      responses:
        "200":
          description: Operation successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpressRouteGatewayList"
              examples:
                ExpressRouteGatewayListByResourceGroup:
                  $ref: "#/components/examples/ExpressRouteGatewayListByResourceGro\
                    up"
      tags:
        - ExpressRouteGateways
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteGateways/{expressRouteGatewayName}":
    delete:
      description: Deletes the specified ExpressRoute gateway in a resource group. An
        ExpressRoute gateway resource can only be deleted when there are no
        connection subresources.
      operationId: ExpressRouteGateways_Delete
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayDelete:
              value: resourceGroupName
        - description: The name of the ExpressRoute gateway.
          in: path
          name: expressRouteGatewayName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayDelete:
              value: expressRouteGatewayName
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayDelete:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayDelete:
              value: subid
      responses:
        "200":
          description: Delete successful.
        "202":
          description: Accepted and the operation will complete asynchronously.
        "204":
          description: Delete successful.
      tags:
        - ExpressRouteGateways
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
    get:
      description: Fetches the details of a ExpressRoute gateway in a resource group.
      operationId: ExpressRouteGateways_Get
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayGet:
              value: resourceGroupName
        - description: The name of the ExpressRoute gateway.
          in: path
          name: expressRouteGatewayName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayGet:
              value: expressRouteGatewayName
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayGet:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayGet:
              value: subid
      responses:
        "200":
          description: Operation succeeded. The operation returns the ExpressRoute gateway.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpressRouteGateway"
              examples:
                ExpressRouteGatewayGet:
                  $ref: "#/components/examples/ExpressRouteGatewayGet"
      tags:
        - ExpressRouteGateways
    put:
      description: Creates or updates a ExpressRoute gateway in a specified resource group.
      operationId: ExpressRouteGateways_CreateOrUpdate
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayCreate:
              value: resourceGroupName
        - description: The name of the ExpressRoute gateway.
          in: path
          name: expressRouteGatewayName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayCreate:
              value: gateway-2
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayCreate:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ExpressRouteGatewayCreate:
              value: subid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExpressRouteGateway"
        description: Parameters required in an ExpressRoute gateway PUT operation.
        required: true
      responses:
        "200":
          description: Update successful. The operation returns the resulting ExpressRoute
            gateway resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpressRouteGateway"
              examples:
                ExpressRouteGatewayCreate:
                  $ref: "#/components/examples/ExpressRouteGatewayCreate"
        "201":
          description: Create successful. The operation returns the resulting ExpressRoute
            gateway resource.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpressRouteGateway"
              examples:
                ExpressRouteGatewayCreate:
                  $ref: "#/components/examples/ExpressRouteGatewayCreate"
      tags:
        - ExpressRouteGateways
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteGateways/{expressRouteGatewayName}/expressRouteConnections":
    get:
      description: Lists ExpressRouteConnections.
      operationId: ExpressRouteConnections_List
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionList:
              value: resourceGroupName
        - description: The name of the ExpressRoute gateway.
          in: path
          name: expressRouteGatewayName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionList:
              value: expressRouteGatewayName
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionList:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionList:
              value: subid
      responses:
        "200":
          description: Request successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpressRouteConnectionList"
              examples:
                ExpressRouteConnectionList:
                  $ref: "#/components/examples/ExpressRouteConnectionList"
      tags:
        - ExpressRouteConnections
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/expressRouteGateways/{expressRouteGatewayName}/expressRouteConnections/{connectionName}":
    delete:
      description: Deletes a connection to a ExpressRoute circuit.
      operationId: ExpressRouteConnections_Delete
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionDelete:
              value: resourceGroupName
        - description: The name of the ExpressRoute gateway.
          in: path
          name: expressRouteGatewayName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionDelete:
              value: expressRouteGatewayName
        - description: The name of the connection subresource.
          in: path
          name: connectionName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionDelete:
              value: connectionName
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionDelete:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionDelete:
              value: subid
      responses:
        "200":
          description: Delete successful.
        "202":
          description: Accepted, and the operation will continue asynchronously.
        "204":
          description: Delete successful.
      tags:
        - ExpressRouteConnections
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: location
    get:
      description: Gets the specified ExpressRouteConnection.
      operationId: ExpressRouteConnections_Get
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionGet:
              value: resourceGroupName
        - description: The name of the ExpressRoute gateway.
          in: path
          name: expressRouteGatewayName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionGet:
              value: expressRouteGatewayName
        - description: The name of the ExpressRoute connection.
          in: path
          name: connectionName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionGet:
              value: connectionName
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionGet:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionGet:
              value: subid
      responses:
        "200":
          description: Request successful. The operation returns the ExpressRouteConnection.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpressRouteConnection"
              examples:
                ExpressRouteConnectionGet:
                  $ref: "#/components/examples/ExpressRouteConnectionGet"
      tags:
        - ExpressRouteConnections
    put:
      description: Creates a connection between an ExpressRoute gateway and an ExpressRoute
        circuit.
      operationId: ExpressRouteConnections_CreateOrUpdate
      parameters:
        - description: The name of the resource group.
          in: path
          name: resourceGroupName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionCreate:
              value: resourceGroupName
        - description: The name of the ExpressRoute gateway.
          in: path
          name: expressRouteGatewayName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionCreate:
              value: gateway-2
        - description: The name of the connection subresource.
          in: path
          name: connectionName
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionCreate:
              value: connectionName
        - description: Client API version.
          in: query
          name: api-version
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionCreate:
              value: 2019-04-01
        - description: The subscription credentials which uniquely identify the Microsoft
            Azure subscription. The subscription ID forms part of the URI for
            every service call.
          in: path
          name: subscriptionId
          required: true
          schema:
            type: string
          examples:
            ExpressRouteConnectionCreate:
              value: subid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExpressRouteConnection"
        description: Parameters required in an ExpressRouteConnection PUT operation.
        required: true
      responses:
        "200":
          description: Update successful. The operation returns the ExpressRouteConnection.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpressRouteConnection"
              examples:
                ExpressRouteConnectionCreate:
                  $ref: "#/components/examples/ExpressRouteConnectionCreate"
        "201":
          description: Create successful. The operation returns the ExpressRouteConnection.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpressRouteConnection"
              examples:
                ExpressRouteConnectionCreate:
                  $ref: "#/components/examples/ExpressRouteConnectionCreate"
      tags:
        - ExpressRouteConnections
      x-ms-long-running-operation: true
      x-ms-long-running-operation-options:
        final-state-via: azure-async-operation
servers:
  - url: https://management.azure.com
components:
  examples:
    ExpressRouteGatewayListBySubscription:
      value:
        value:
          - etag: w/\00000000-0000-0000-0000-000000000000\
            id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteGateways/expressRouteGatewayName
            location: westus
            name: expressRouteGatewayName
            properties:
              autoScaleConfiguration:
                bounds:
                  min: 2
              expressRouteConnections:
                - id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteGateways/expressRouteGatewayName/expressRouteConnections/connectionName
                  name: connectionName
                  properties:
                    authorizationKey: f28e9c99-78d8-4248-a855-c54cf6beb99d
                    expressRouteCircuitPeering:
                      id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteCircuits/circuitName/peerings/AzurePrivatePeering
                    provisioningState: Provisioned
                    routingWeight: 1
              provisioningState: Succeeded
              virtualHub:
                id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/virtualHubs/virtualHubName
            type: Microsoft.Network/expressRouteGateways
    ExpressRouteGatewayListByResourceGroup:
      value:
        value:
          - etag: w/\00000000-0000-0000-0000-000000000000\
            id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteGateways/expressRouteGatewayName
            location: westus
            name: expressRouteGatewayName
            properties:
              autoScaleConfiguration:
                bounds:
                  min: 2
              expressRouteConnections:
                - id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteGateways/expressRouteGatewayName/expressRouteConnections/connectionName
                  name: connectionName
                  properties:
                    authorizationKey: f28e9c99-78d8-4248-a855-c54cf6beb99d
                    expressRouteCircuitPeering:
                      id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteCircuits/circuitName/peerings/AzurePrivatePeering
                    provisioningState: Provisioned
                    routingWeight: 1
              provisioningState: Succeeded
              virtualHub:
                id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/virtualHubs/virtualHubName
            type: Microsoft.Network/expressRouteGateways
    ExpressRouteGatewayGet:
      value:
        etag: w/\00000000-0000-0000-0000-000000000000\
        id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteGateways/expressRouteGatewayName
        location: westus
        name: expressRouteGatewayName
        properties:
          provisioningState: Succeeded
          virtualHub:
            id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/virtualHubs/virtualHubName
        type: Microsoft.Network/expressRouteGateways
    ExpressRouteGatewayCreate:
      value:
        etag: w/\00000000-0000-0000-0000-000000000000\
        id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteGateways/gateway-2
        location: westus
        name: gateway-2
        properties:
          autoScaleConfiguration:
            bounds:
              min: 3
          provisioningState: Succeeded
          virtualHub:
            id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/virtualHubs/virtualHubName
        type: Microsoft.Network/expressRouteGateways
    ExpressRouteConnectionList:
      value:
        value:
          - id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteGateways/expressRouteGatewayName/expressRouteConnections/connectionName
            name: connectionName
            properties:
              authorizationKey: authorizationKey
              expressRouteCircuitPeering:
                id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteCircuits/circuitName/peerings/AzurePrivatePeering
              provisioningState: Provisioned
              routingWeight: 1
    ExpressRouteConnectionGet:
      value:
        id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteGateways/expressRouteGatewayName/expressRouteConnections/connectionName
        name: connectionName
        properties:
          authorizationKey: authorizationKey
          expressRouteCircuitPeering:
            id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteCircuits/circuitName/peerings/AzurePrivatePeering
          provisioningState: Provisioned
          routingWeight: 1
    ExpressRouteConnectionCreate:
      value:
        id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteGateways/gateway-2/expressRouteConnections/connectionName
        name: connectionName
        properties:
          authorizationKey: authorizationKey
          expressRouteCircuitPeering:
            id: /subscriptions/subid/resourceGroups/resourceGroupName/providers/Microsoft.Network/expressRouteCircuits/circuitName/peerings/AzurePrivatePeering
          provisioningState: Provisioned
          routingWeight: 2
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ExpressRouteCircuitPeeringId:
      description: ExpressRoute circuit peering identifier.
      properties:
        id:
          description: The ID of the ExpressRoute circuit peering.
          type: string
    ExpressRouteConnection:
      allOf:
        - description: Reference to another subresource.
          properties:
            id:
              description: Resource ID.
              type: string
          x-ms-azure-resource: true
      description: ExpressRouteConnection resource.
      properties:
        name:
          description: The name of the resource.
          type: string
        properties:
          $ref: "#/components/schemas/ExpressRouteConnectionProperties"
      required:
        - name
    ExpressRouteConnectionId:
      description: The ID of the ExpressRouteConnection.
      properties:
        id:
          description: The ID of the ExpressRouteConnection.
          readOnly: true
          type: string
    ExpressRouteConnectionList:
      description: ExpressRouteConnection list.
      properties:
        value:
          description: The list of ExpressRoute connections.
          items:
            $ref: "#/components/schemas/ExpressRouteConnection"
          type: array
    ExpressRouteConnectionProperties:
      description: Properties of the ExpressRouteConnection subresource.
      properties:
        authorizationKey:
          description: Authorization key to establish the connection.
          type: string
        expressRouteCircuitPeering:
          $ref: "#/components/schemas/ExpressRouteCircuitPeeringId"
        provisioningState:
          description: The current provisioning state.
          enum:
            - Succeeded
            - Updating
            - Deleting
            - Failed
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: ProvisioningState
        routingWeight:
          description: The routing weight associated to the connection.
          type: integer
      required:
        - expressRouteCircuitPeering
    ExpressRouteGateway:
      allOf:
        - description: Common resource representation.
          properties:
            id:
              description: Resource ID.
              type: string
            location:
              description: Resource location.
              type: string
            name:
              description: Resource name.
              readOnly: true
              type: string
            tags:
              additionalProperties:
                type: string
              description: Resource tags.
              type: object
            type:
              description: Resource type.
              readOnly: true
              type: string
          x-ms-azure-resource: true
      description: ExpressRoute gateway resource.
      properties:
        etag:
          description: A unique read-only string that changes whenever the resource is
            updated.
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/ExpressRouteGatewayProperties"
    ExpressRouteGatewayList:
      description: List of ExpressRoute gateways.
      properties:
        value:
          description: List of ExpressRoute gateways.
          items:
            $ref: "#/components/schemas/ExpressRouteGateway"
          type: array
    ExpressRouteGatewayProperties:
      description: ExpressRoute gateway resource properties.
      properties:
        autoScaleConfiguration:
          description: Configuration for auto scaling.
          properties:
            bounds:
              description: Minimum and maximum number of scale units to deploy.
              properties:
                max:
                  description: Maximum number of scale units deployed for ExpressRoute
                    gateway.
                  type: integer
                min:
                  description: Minimum number of scale units deployed for ExpressRoute
                    gateway.
                  type: integer
        expressRouteConnections:
          description: List of ExpressRoute connections to the ExpressRoute gateway.
          items:
            $ref: "#/components/schemas/ExpressRouteConnection"
          readOnly: true
          type: array
        provisioningState:
          description: The current provisioning state.
          enum:
            - Succeeded
            - Updating
            - Deleting
            - Failed
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: ProvisioningState
        virtualHub:
          $ref: "#/components/schemas/VirtualHubId"
      required:
        - virtualHub
    VirtualHubId:
      description: Virtual Hub identifier.
      properties:
        id:
          description: The resource URI for the Virtual Hub where the ExpressRoute gateway
            is or will be deployed. The Virtual Hub resource and the
            ExpressRoute gateway resource reside in the same subscription.
          type: string
