openapi: 3.0.0
info:
  description: Specification for ManagedServices.
  title: ManagedServicesClient
  version: 2019-06-01
  x-apisguru-categories:
    - cloud
  x-logo:
    url: https://assets.onestore.ms/cdnfiles/onestorerolling-1606-01000/shell/v3/images/logo/microsoft.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/managedservices/resource-manager/Microsoft.ManagedServices/stable/2019-06-01/managedservices.json
      version: "2.0"
  x-preferred: true
  x-providerName: azure.com
  x-serviceName: managedservices
  x-tags:
    - Azure
    - Microsoft
security:
  - azure_auth:
      - user_impersonation
paths:
  /providers/Microsoft.ManagedServices/operations:
    get:
      description: Gets a list of the operations.
      operationId: Operations_List
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK - Returns a list of operations.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OperationList"
              examples:
                Get Registration Operations:
                  $ref: "#/components/examples/Get_Registration_Operations"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - Operations
  "/{scope}/providers/Microsoft.ManagedServices/registrationAssignments":
    get:
      description: Gets a list of the registration assignments.
      operationId: RegistrationAssignments_List
      parameters:
        - $ref: "#/components/parameters/ScopeParameter"
        - $ref: "#/components/parameters/ExpandRegistrationDefinition"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK - Returns a list of the registration assignments.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationAssignmentList"
              examples:
                Get Registration Assignments:
                  $ref: "#/components/examples/Get_Registration_Assignments"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - RegistrationAssignments
      x-ms-pageable:
        nextLinkName: nextLink
  "/{scope}/providers/Microsoft.ManagedServices/registrationAssignments/{registrationAssignmentId}":
    delete:
      description: Deletes the specified registration assignment.
      operationId: RegistrationAssignments_Delete
      parameters:
        - $ref: "#/components/parameters/ScopeParameter"
        - $ref: "#/components/parameters/RegistrationAssignmentIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK - The registration assignment is deleted.
        "202":
          description: Accepted - The registration assignment deletion operation is
            accepted.
        "204":
          description: No Content- The registration assignment does not exist.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - RegistrationAssignments
      x-ms-long-running-operation: true
    get:
      description: Gets the details of specified registration assignment.
      operationId: RegistrationAssignments_Get
      parameters:
        - $ref: "#/components/parameters/ScopeParameter"
        - $ref: "#/components/parameters/RegistrationAssignmentIdParameter"
        - $ref: "#/components/parameters/ExpandRegistrationDefinition"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK - Returns the registration assignment.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationAssignment"
              examples:
                Get Registration Assignment:
                  $ref: "#/components/examples/Get_Registration_Assignment"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - RegistrationAssignments
    put:
      description: Creates or updates a registration assignment.
      operationId: RegistrationAssignments_CreateOrUpdate
      parameters:
        - $ref: "#/components/parameters/ScopeParameter"
        - $ref: "#/components/parameters/RegistrationAssignmentIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegistrationAssignment"
        description: The parameters required to create new registration assignment.
        required: true
      responses:
        "200":
          description: Ok - Returns information about the updated registration assignment.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationAssignment"
              examples:
                Put Registration Assignment:
                  $ref: "#/components/examples/Put_Registration_Assignment"
        "201":
          description: Created - Returns information about the created registration
            assignment.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationAssignment"
              examples:
                Put Registration Assignment:
                  $ref: "#/components/examples/Put_Registration_Assignment"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - RegistrationAssignments
      x-ms-long-running-operation: true
  "/{scope}/providers/Microsoft.ManagedServices/registrationDefinitions":
    get:
      description: Gets a list of the registration definitions.
      operationId: RegistrationDefinitions_List
      parameters:
        - $ref: "#/components/parameters/ScopeParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK - Returns a list of the registration definitions.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationDefinitionList"
              examples:
                Get Registration Definitions:
                  $ref: "#/components/examples/Get_Registration_Definitions"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - RegistrationDefinitions
      x-ms-pageable:
        nextLinkName: nextLink
  "/{scope}/providers/Microsoft.ManagedServices/registrationDefinitions/{registrationDefinitionId}":
    delete:
      description: Deletes the registration definition.
      operationId: RegistrationDefinitions_Delete
      parameters:
        - $ref: "#/components/parameters/registrationDefinitionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/ScopeParameter"
      responses:
        "200":
          description: OK - The registration definition is deleted.
        "204":
          description: No Content- The registration definition does not exist.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - RegistrationDefinitions
    get:
      description: Gets the registration definition details.
      operationId: RegistrationDefinitions_Get
      parameters:
        - $ref: "#/components/parameters/ScopeParameter"
        - $ref: "#/components/parameters/registrationDefinitionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
      responses:
        "200":
          description: OK - Returns the complete registration definition with plan details.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationDefinition"
              examples:
                Get Registration Definition:
                  $ref: "#/components/examples/Get_Registration_Definition"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - RegistrationDefinitions
    put:
      description: Creates or updates a registration definition.
      operationId: RegistrationDefinitions_CreateOrUpdate
      parameters:
        - $ref: "#/components/parameters/registrationDefinitionIdParameter"
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/ScopeParameter"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegistrationDefinition"
        description: The parameters required to create new registration definition.
        required: true
      responses:
        "200":
          description: Ok - Returns information about the updated registration definition.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationDefinition"
              examples:
                Put Registration Definition:
                  $ref: "#/components/examples/Put_Registration_Definition"
        "201":
          description: Created - Returns information about the created registration
            definition.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationDefinition"
              examples:
                Put Registration Definition:
                  $ref: "#/components/examples/Put_Registration_Definition"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      tags:
        - RegistrationDefinitions
      x-ms-long-running-operation: true
servers:
  - url: https://management.azure.com
components:
  examples:
    Get_Registration_Operations:
      value:
        value:
          - display:
              description: Retrieves a list of Managed Services registration definitions.
              operation: List Managed Services Registration Definitions
              provider: Microsoft Managed Services
              resource: Managed Services Registration Definition
            name: Microsoft.ManagedServices/registrationDefinitions/read
    Get_Registration_Assignments:
      value:
        value:
          - id: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationAssignments/484a7d5f-9729-4b87-bc9b-26610985a013
            name: 484a7d5f-9729-4b87-bc9b-26610985a013
            properties:
              provisioningState: Succeeded
              registrationDefinition:
                id: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-8e081c90ada2
                name: 26c128c2-fefa-4340-9bb1-8e081c90ada2
                plan:
                  name: addesai-plan
                  product: test
                  publisher: marketplace-test
                  version: 1.0.0
                properties:
                  authorizations:
                    - principalId: f98d86a2-4cc4-4e9d-ad47-b3e80a1bcdfc
                      roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
                  description: Test
                  managedByTenantId: 83abe5cd-bcc3-441a-bd86-e6a75360cecc
                  managedByTenantName: Contoso Corp.
                  manageeTenantId: 01c0bcd5-4f47-4e4b-b492-418b7e2a8854
                  manageeTenantName: test_test_aad_SbtFhyGiLHPFm
                  provisioningState: Succeeded
                  registrationDefinitionName: DefinitionName
                type: Microsoft.ManagedServices/registrationDefinitions
              registrationDefinitionId: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-8e081c90ada2
            type: Microsoft.ManagedServices/registrationAssignments
    Get_Registration_Assignment:
      value:
        id: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationAssignments/484a7d5f-9729-4b87-bc9b-26610985a013
        name: 484a7d5f-9729-4b87-bc9b-26610985a013
        properties:
          provisioningState: Succeeded
          registrationDefinition:
            id: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-8e081c90ada2
            name: 26c128c2-fefa-4340-9bb1-8e081c90ada2
            plan:
              name: addesai-plan
              product: test
              publisher: marketplace-test
              version: 1.0.0
            properties:
              authorizations:
                - principalId: f98d86a2-4cc4-4e9d-ad47-b3e80a1bcdfc
                  roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
              description: Test
              managedByTenantId: 83abe5cd-bcc3-441a-bd86-e6a75360cecc
              managedByTenantName: Contoso Corp.
              manageeTenantId: 01c0bcd5-4f47-4e4b-b492-418b7e2a8854
              manageeTenantName: test_test_aad_SbtFhyGiLHPFm
              provisioningState: Succeeded
              registrationDefinitionName: DefinitionName
            type: Microsoft.ManagedServices/registrationDefinitions
          registrationDefinitionId: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-8e081c90ada2
        type: Microsoft.ManagedServices/registrationAssignments
    Put_Registration_Assignment:
      value:
        id: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationAssignments/484a7d5f-9729-4b87-bc9b-26610985a013
        name: 484a7d5f-9729-4b87-bc9b-26610985a013
        properties:
          provisioningState: Succeeded
          registrationDefinitionId: /subscriptions/0afefe50-734e-4610-8c82-a144aff49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-8e081c90ada2
        type: Microsoft.ManagedServices/registrationAssignments
    Get_Registration_Definitions:
      value:
        value:
          - id: /subscriptions/0afefe50-734e-4610-8a82-a144ahf49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-6e081c90ada2
            name: 26c128c2-fefa-4340-9bb1-6e081c90ada2
            plan:
              name: addesai-plan
              product: test
              publisher: marketplace-test
              version: 1.0.0
            properties:
              authorizations:
                - principalId: f98g86a2-4cc4-4e6d-ad47-b3e80a1bcdfc
                  roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
              description: Test
              managedByTenantId: 83ace5cd-bcc3-441a-hd86-e6a75360cecc
              managedByTenantName: Test Tenant
              provisioningState: Succeeded
              registrationDefinitionName: DefinitionName
            type: Microsoft.ManagedServices/registrationDefinitions
    Get_Registration_Definition:
      value:
        id: /subscriptions/0afefe50-734e-4610-8a82-a144ahf49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-6e081c90ada2
        name: 26c128c2-fefa-4340-9bb1-6e081c90ada2
        plan:
          name: addesai-plan
          product: test
          publisher: marketplace-test
          version: 1.0.0
        properties:
          authorizations:
            - principalId: f98g86a2-4cc4-4e6d-ad47-b3e80a1bcdfc
              roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
          description: Test
          managedByTenantId: 83ace5cd-bcc3-441a-hd86-e6a75360cecc
          managedByTenantName: Test Tenant
          provisioningState: Succeeded
          registrationDefinitionName: DefinitionName
        type: Microsoft.ManagedServices/registrationDefinitions
    Put_Registration_Definition:
      value:
        id: /subscriptions/0afefe50-734e-4610-8a82-a144ahf49dea/providers/Microsoft.ManagedServices/registrationDefinitions/26c128c2-fefa-4340-9bb1-6e081c90ada2
        name: 26c128c2-fefa-4340-9bb1-6e081c90ada2
        plan:
          name: addesai-plan
          product: test
          publisher: marketplace-test
          version: 1.0.0
        properties:
          authorizations:
            - principalId: f98g86a2-4cc4-4e6d-ad47-b3e80a1bcdfc
              roleDefinitionId: acdd72a7-3385-48ef-bd42-f606fba81ae7
          description: Test
          managedByTenantId: 83ace5cd-bcc3-441a-hd86-e6a75360cecc
          managedByTenantName: Test Tenant
          provisioningState: Succeeded
          registrationDefinitionName: DefinitionName
        type: Microsoft.ManagedServices/registrationDefinitions
  parameters:
    ApiVersionParameter:
      description: The API version to use for this operation.
      in: query
      name: api-version
      required: true
      schema:
        type: string
      examples:
        Get Registration Operations:
          value: 2019-06-01
        Get Registration Assignments:
          value: 2019-06-01
        Delete Registration Assignment:
          value: 2019-06-01
        Get Registration Assignment:
          value: 2019-06-01
        Put Registration Assignment:
          value: 2019-06-01
        Get Registration Definitions:
          value: 2019-06-01
        Delete Registration Definition:
          value: 2019-06-01
        Get Registration Definition:
          value: 2019-06-01
        Put Registration Definition:
          value: 2019-06-01
    ExpandRegistrationDefinition:
      description: Tells whether to return registration definition details also along with
        registration assignment details.
      in: query
      name: $expandRegistrationDefinition
      x-ms-parameter-location: method
      schema:
        type: boolean
    RegistrationAssignmentIdParameter:
      description: Guid of the registration assignment.
      in: path
      name: registrationAssignmentId
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Delete Registration Assignment:
          value: 26c128c2-fefa-4340-9bb1-6e081c90ada2
        Get Registration Assignment:
          value: 26c128c2-fefa-4340-9bb1-6e081c90ada2
        Put Registration Assignment:
          value: 26c128c2-fefa-4340-9bb1-6e081c90ada2
    ScopeParameter:
      description: Scope of the resource.
      in: path
      name: scope
      required: true
      x-ms-parameter-location: method
      x-ms-skip-url-encoding: true
      schema:
        type: string
      examples:
        Get Registration Assignments:
          value: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
        Delete Registration Assignment:
          value: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
        Get Registration Assignment:
          value: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
        Put Registration Assignment:
          value: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
        Get Registration Definitions:
          value: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
        Delete Registration Definition:
          value: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
        Get Registration Definition:
          value: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
        Put Registration Definition:
          value: subscription/0afefe50-734e-4610-8a82-a144ahf49dea
    registrationDefinitionIdParameter:
      description: Guid of the registration definition.
      in: path
      name: registrationDefinitionId
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
      examples:
        Delete Registration Definition:
          value: 26c128c2-fefa-4340-9bb1-6e081c90ada2
        Get Registration Definition:
          value: 26c128c2-fefa-4340-9bb1-6e081c90ada2
        Put Registration Definition:
          value: 26c128c2-fefa-4340-9bb1-6e081c90ada2
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    Authorization:
      description: Authorization tuple containing principal Id (of user/service
        principal/security group) and role definition id.
      properties:
        principalId:
          description: Principal Id of the security group/service principal/user that would
            be assigned permissions to the projected subscription
          type: string
        roleDefinitionId:
          description: The role definition identifier. This role will define all the
            permissions that the security group/service principal/user must have
            on the projected subscription. This role cannot be an owner role.
          type: string
      required:
        - principalId
        - roleDefinitionId
      type: object
    ErrorResponse:
      description: Error response.
      properties:
        error:
          description: Error response indicates Azure Resource Manager is not able to
            process the incoming request. The reason is provided in the error
            message.
          properties:
            code:
              description: Error code.
              type: string
            message:
              description: Error message indicating why the operation failed.
              type: string
          readOnly: true
          required:
            - code
            - message
          type: object
    Operation:
      description: Object that describes a single Microsoft.ManagedServices operation.
      properties:
        display:
          description: The object that represents the operation.
          properties:
            description:
              description: Description of the operation.
              type: string
            operation:
              description: "Operation type: Read, write, delete, etc."
              type: string
            provider:
              description: "Service provider: Microsoft.ManagedServices"
              type: string
            resource:
              description: "Resource on which the operation is performed: Registration
                definition, registration assignment etc."
              type: string
          readOnly: true
        name:
          description: "Operation name: {provider}/{resource}/{operation}"
          readOnly: true
          type: string
      type: object
    OperationList:
      description: List of the operations.
      properties:
        value:
          description: List of Microsoft.ManagedServices operations.
          items:
            $ref: "#/components/schemas/Operation"
          readOnly: true
          type: array
      type: object
    Plan:
      description: Plan details for the managed services.
      properties:
        name:
          description: The plan name.
          type: string
        product:
          description: The product code.
          type: string
        publisher:
          description: The publisher ID.
          type: string
        version:
          description: The plan's version.
          type: string
      required:
        - name
        - publisher
        - product
        - version
      type: object
    RegistrationAssignment:
      description: Registration assignment.
      properties:
        id:
          description: The fully qualified path of the registration assignment.
          readOnly: true
          type: string
        name:
          description: Name of the registration assignment.
          readOnly: true
          type: string
        properties:
          $ref: "#/components/schemas/RegistrationAssignmentProperties"
        type:
          description: Type of the resource.
          readOnly: true
          type: string
      type: object
      x-ms-azure-resource: true
    RegistrationAssignmentList:
      description: List of registration assignments.
      properties:
        nextLink:
          description: Link to next page of registration assignments.
          readOnly: true
          type: string
        value:
          description: List of registration assignments.
          items:
            $ref: "#/components/schemas/RegistrationAssignment"
          readOnly: true
          type: array
    RegistrationAssignmentProperties:
      description: Properties of a registration assignment.
      properties:
        provisioningState:
          description: Current state of the registration assignment.
          enum:
            - NotSpecified
            - Accepted
            - Running
            - Ready
            - Creating
            - Created
            - Deleting
            - Deleted
            - Canceled
            - Failed
            - Succeeded
            - Updating
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: ProvisioningState
        registrationDefinition:
          description: Registration definition inside registration assignment.
          properties:
            id:
              description: Fully qualified path of the registration definition.
              readOnly: true
              type: string
            name:
              description: Name of the registration definition.
              readOnly: true
              type: string
            plan:
              $ref: "#/components/schemas/Plan"
            properties:
              description: Properties of registration definition inside registration
                assignment.
              properties:
                authorizations:
                  description: Authorization tuple containing principal id of the
                    user/security group or service principal and id of the
                    build-in role.
                  items:
                    $ref: "#/components/schemas/Authorization"
                  type: array
                description:
                  description: Description of the registration definition.
                  type: string
                managedByTenantId:
                  description: Id of the managedBy tenant.
                  type: string
                managedByTenantName:
                  description: Name of the managedBy tenant.
                  type: string
                manageeTenantId:
                  description: Id of the home tenant.
                  type: string
                manageeTenantName:
                  description: Name of the home tenant.
                  type: string
                provisioningState:
                  description: Current state of the registration definition.
                  enum:
                    - NotSpecified
                    - Accepted
                    - Running
                    - Ready
                    - Creating
                    - Created
                    - Deleting
                    - Deleted
                    - Canceled
                    - Failed
                    - Succeeded
                    - Updating
                  type: string
                  x-ms-enum:
                    modelAsString: true
                    name: ProvisioningState
                registrationDefinitionName:
                  description: Name of the registration definition.
                  type: string
            type:
              description: Type of the resource
                (Microsoft.ManagedServices/registrationDefinitions).
              readOnly: true
              type: string
          readOnly: true
          type: object
        registrationDefinitionId:
          description: Fully qualified path of the registration definition.
          type: string
      required:
        - registrationDefinitionId
      type: object
    RegistrationDefinition:
      description: Registration definition.
      properties:
        id:
          description: Fully qualified path of the registration definition.
          readOnly: true
          type: string
        name:
          description: Name of the registration definition.
          readOnly: true
          type: string
        plan:
          $ref: "#/components/schemas/Plan"
        properties:
          $ref: "#/components/schemas/RegistrationDefinitionProperties"
        type:
          description: Type of the resource.
          readOnly: true
          type: string
      type: object
      x-ms-azure-resource: true
    RegistrationDefinitionList:
      description: List of registration definitions.
      properties:
        nextLink:
          description: Link to next page of registration definitions.
          readOnly: true
          type: string
        value:
          description: List of registration definitions.
          items:
            $ref: "#/components/schemas/RegistrationDefinition"
          readOnly: true
          type: array
    RegistrationDefinitionProperties:
      description: Properties of a registration definition.
      properties:
        authorizations:
          description: Authorization tuple containing principal id of the user/security
            group or service principal and id of the build-in role.
          items:
            $ref: "#/components/schemas/Authorization"
          type: array
        description:
          description: Description of the registration definition.
          type: string
        managedByTenantId:
          description: Id of the managedBy tenant.
          type: string
        managedByTenantName:
          description: Name of the managedBy tenant.
          readOnly: true
          type: string
        provisioningState:
          description: Current state of the registration definition.
          enum:
            - NotSpecified
            - Accepted
            - Running
            - Ready
            - Creating
            - Created
            - Deleting
            - Deleted
            - Canceled
            - Failed
            - Succeeded
            - Updating
          readOnly: true
          type: string
          x-ms-enum:
            modelAsString: true
            name: ProvisioningState
        registrationDefinitionName:
          description: Name of the registration definition.
          type: string
      required:
        - managedByTenantId
        - authorizations
      type: object
